COMMON:
    fps: 5
    use_gpu: True
    imgs_path: "data/test/frames/"
    pcm_path: "data/test/audio/11.pcm"
    feature_path: "data/test/feature/output_11.pkl"
    label_dic: 'configs/index_label_football_8.json'
    props_path: "tmp/bmn.txt"
    classify_path: "tmp/result.json"
    clssify_topk: 1

TSN:
    name: "TSN"
    weight_path: "/home/work/checkpoints/models_tsn/TSN_epoch36.pdparams"
    format: "jpg"
    num_classes: 8  # 16
    seg_num: 7
    seglen: 1
    image_mean: [0.485, 0.456, 0.406]
    image_std: [0.229, 0.224, 0.225]
    num_layers: 50
    short_size: 256
    target_size: 224
    num_reader_threads: 12
    buf_size: 1024
    batch_size: 128  # 32
    image_scale: 2048
    audio_scale: 640

AUDIO:
    name: "AUDIO"
    weight_path: "/home/work/checkpoints/models_audio/audio.pdparams"
    sample_rate: 16000
    pcm_file: "tmp/1.pcm"
    feature_names: ['audio']
    feature_dims: [[50, 64]]
    lstm_size_audio: 1024
    batch_size: 32

BMN:
    name: "BMN"
    subset: "test"
    weight_path: "/home/work/checkpoints/models_bmn/BMN_epoch19.pdparams"
    window_step: 200
    tscale: 200
    dscale: 200
    feat_dim: 2048
    prop_boundary_ratio: 0.5
    num_sample: 32
    num_sample_perbin: 3
    batch_size: 1
    num_threads: 8
    nms_thread: 0.7
    score_thread: 0.01
    output_path: "logs/BMN_results"
    result_path: "logs/BMN_results"

ACTION:
    name: "ActionNet"
    dataset: "lstmdata"
    bone_nework: None
    subset: "test"
    drop_rate: 0.5
    feature_num: 2
    feature_names: ['rgb', 'audio']
    feature_dims: [2048, 1024]
    embedding_size: 512
    lstm_size_img: 2048
    lstm_size_audio: 1024
    num_classes: 8
    topk: 1
    with_bn: True
    weight_path: "/home/work/checkpoints/models_lstm/ActionNet_epoch14_acc82.34873749404478.pdparams"
    batch_size: 1
    nms_thread: 0.01
    nms_offset: 10

    classify_score_thread: 0.05     # 0.15
    iou_score_thread: 0.1           # 0.4
